<?php
$this->setTitle('Đổi mật khẩu');
?>

<style>
    #frmMain .form-group{max-width: 600px;}
</style>

<div class="row">
    <div class="col-xs-12">
        <h1 class="page-header">Đổi mật khẩu</h1>
    </div>
</div>

<?php if (isset($success)): ?>
    <div class="alert alert-success">
        Đổi mật khẩu thành công.
    </div>
<?php endif; ?>
<?php if (isset($error)): ?>
    <?php
    switch ($error) {
        case 'wrongCurrent':
            $msg = 'Sai mật khẩu hiện tại.';
            break;
        case 'wrongRePass':
            $msg = 'Mật khẩu nhập lại không khớp.';
            break;
        default:
            $msg = 'Lỗi khác';
    }
    ?>
    <div class="alert alert-danger"><?php echo $msg ?></div>
<?php endif; ?>
<form method="post" class="form-validate form-horizontal" id="frmMain">
    <div class="row form-group">
        <label class="control-label col-xs-4" for="txtCurrent"><?php echo static::HTML_REQUIRED ?> Mật khẩu cũ:</label>
        <div class="col-xs-8">
            <input type="password" class="form-control" name="txtCurrent" id="txtCurrent"  required/>
        </div>
    </div>
    <div class="row form-group">
        <label class="control-label col-xs-4" for="txtNew"><?php echo static::HTML_REQUIRED ?> Mật khẩu mới:</label>
        <div class="col-xs-8">
            <input type="password" class="form-control" name="txtNew" id="txtNew"  required minlength="6"/>
        </div>
    </div>
    <div class="row form-group">
        <label class="control-label col-xs-4" for="txtRe"><?php echo static::HTML_REQUIRED ?> Nhập lại mật khẩu:</label>
        <div class="col-xs-8">
            <input type="password" class="form-control" name="txtRe" id="txtRe"  required minlength="6"/>
        </div>
    </div>
    <hr>
    <div class="row form-group">
        <div class="col-xs-8 col-xs-offset-4">
            <button type="submit" class="btn btn-primary" onclick="changePass(this)">Đổi mật khẩu</button>
            <a href="<?php echo $lastPage ?>" class="btn btn-default">Hủy bỏ</a>
        </div>
    </div>
</form>

<script>
    function changePass() {
        var form = document.getElementById('frmMain');
        if (!form.checkValidity())
            return;
        form.submit();
    }
</script>
