<form method="post" ng-submit="submitDep($event)" class="form-horizontal form-validate">
    <div id="modal-dep" class="modal fade" tabindex="-1" role="dialog" ng-dom="modalDep">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Đơn vị/Phòng ban</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="editDep" class="col-xs-3 control-label">Trực thuộc:</label>
                        <div class="col-xs-9">
                            <div class="parent-dep">
                                <input type="text" class="form-control" name="editDep" id="editDep" readonly placeholder="Chọn đơn vị"
                                       value="{{editingDep.parentDep.depName}}" ng-click="pickEditDep()"/>
                                <span ng-if="editingDep.parentDep && editingDep.parentDep.pk" ng-click="clearParentDep()">&times;</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="editDepName" class="control-label col-xs-3"><?php echo static::HTML_REQUIRED ?> Tên đơn vị:</label>
                        <div class="col-xs-9">
                            <input type="text" class="form-control" name="editDepName" id="editDepName" ng-model="editingDep.depName" required/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="editDepCode" class="control-label col-xs-3">Mã đơn vị:</label>
                        <div class="col-xs-9">
                            <input type="text" class="form-control" name="editDepCode" id="editDepCode" ng-model="editingDep.depCode" required/>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-9 col-xs-offset-3">
                            <label class="check">
                                <input type="checkbox" ng-model="editingDep.stt"/>
                                <before></before>
                                <after></after>
                                &nbsp;Hoạt động 
                            </label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <i class="fa fa-circle-o-notch fa-spin" ng-if="ajax.submit"></i>
                    <label class="check">
                        <input type="checkbox" ng-model="editingDep.insertAndOpen"/>
                        <before></before>
                        <after></after>
                        &nbsp;Ghi & thêm mới&nbsp;
                    </label>
                    <button type="button" class="btn btn-default" data-dismiss="modal" ng-disabled="ajax.submit">Hủy bỏ</button>
                    <button type="submit" class="btn btn-primary" ng-disabled="ajax.submit">Ghi lại</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</form>